# Generated by Django 5.1.5 on 2025-01-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
