# Generated by Django 5.1.5 on 2025-01-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_tenant_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
